### ISSUE TITLE
Cannot import name "HomeAssistant" from hass_client.

### ISSUE THREAD

**Issue by CallumToddYTL** [marcelveldt/python-hass-client#77]
We tried running the file unchanged after installing the packages and running the **setup.py** file, and got the error presented in the title.

![image](https://user-images.githubusercontent.com/106147214/185594217-f26c8d0c-e8a2-4251-86a2-f537eee803ca.png)

I see this is 2 years old, has there been changes/updates that makes this solution obsolete? 

This is in the test.py file...

**Comment by marcelveldt** [comment]
This project has been completely refactored. Please try again with version 1.0.0 which I'm about to release.
It will expose HomeAssistantClient btw, not HomeAssistant
